export type Comment = { author: string; text: string; time: string };
export type Topic = {
  title: string;
  author: string;
  time: string;
  replies: number;
  content: string;
  comments: Comment[];
};

export const sampleComments = [
    '¡Excelente pregunta! Creo que...',
    'Estoy de acuerdo. A mí me ha funcionado...',
    'Por mi experiencia, lo que mejor sirve es...',
    'Esa es una buena forma de verlo, aunque yo preferiría...',
    'He escuchado lo mismo, pero también recomiendo...',
    '¿Alguien tiene otra perspectiva sobre esto?',
    'Muy buen punto. Me has dado algo en qué pensar.',
    'Podrías probar con...',
    '¡Gracias por el consejo, lo aplicaré!',
    'No lo había pensado así. Muy útil.',
    'A mi me pasa lo mismo, ¿qué hiciste para solucionarlo?',
    'Es importante considerar la experiencia y el tipo de proyecto.'
];

export const sampleAuthors: string[] = [
  "Juan G.", "Sofía R.", "Carlos V.", "Ana P.", "Pedro A.", "Martín T.", "Laura D.", "Daniela G."
];

export function getRandomInt(min: number, max: number): number {
  const lo = Math.ceil(min);
  const hi = Math.floor(max);
  return Math.floor(Math.random() * (hi - lo + 1)) + lo;
}

export function generateRandomComments(count: number): Comment[] {
  const n = Math.max(0, Math.floor(count));
  const comments: Comment[] = [];
  for (let i = 0; i < n; i++) {
    const author = sampleAuthors[getRandomInt(0, sampleAuthors.length - 1)];
    const text = sampleComments[getRandomInt(0, sampleComments.length - 1)];
    const timeAgo = getRandomInt(1, 60);
    comments.push({ author, text, time: `Hace ${timeAgo} minutos` });
  }
  return comments;
}

export let forumTopics = [
    { title: '¿Cuál es el mejor software para diseño UI/UX?', author: 'Matias S.', time: 'Hace 3 horas', replies: 5, content: 'Hola, estoy empezando en el diseño de interfaces y me gustaría saber cuál es la herramienta más popular y recomendada para trabajar...', comments: [ {author: 'Carlos V.', text: 'Figma es la más usada y es excelente para colaboración.', time: 'Hace 5 min'}, {author: 'Ana P.', text: 'Yo uso Sketch para diseño de apps, pero Figma también es muy buena.', time: 'Hace 10 min'}, {author: 'Pedro A.', text: 'Adobe XD es una buena opción, tiene una curva de aprendizaje sencilla.', time: 'Hace 12 min'}, {author: 'Sofía L.', text: 'Figma sin duda, especialmente si trabajas en equipo.', time: 'Hace 15 min'}, {author: 'Juan M.', text: 'He probado todas, y Figma es la más completa. Además la versión gratuita es muy buena.', time: 'Hace 20 min'} ]},
    { title: 'Consejos para fijar precios en proyectos freelance', author: 'Laura P.', time: 'Hace 1 día', replies: 7, content: 'He tenido problemas para cotizar mis servicios. ¿Alguien podría compartir cómo calculan sus tarifas por proyecto o por hora? ¡Toda ayuda es bienvenida!', comments: [ {author: 'Juan G.', text: 'Yo calculo mis horas por el valor que me gustaría ganar al mes.', time: 'Hace 10 min'}, {author: 'Sofía R.', text: 'Investiga los precios de tu competencia y no te subestimes.', time: 'Hace 12 min'}, {author: 'Carlos V.', text: 'Es importante considerar la experiencia, el tipo de proyecto y el valor que le aportas al cliente.', time: 'Hace 15 min'}, {author: 'Ana P.', text: 'Para mí, la mejor forma es con un precio fijo, así el cliente sabe desde el inicio.', time: 'Hace 18 min'}, {author: 'Pedro A.', text: 'También es bueno estimar una cantidad de horas y cobrar por esa base, para luego ver si se necesita más tiempo.', time: 'Hace 20 min'}, {author: 'Laura D.', text: 'Yo cobro el 50% al inicio y el resto al finalizar. Así ambas partes se comprometen.', time: 'Hace 25 min'}, {author: 'Daniela G.', text: 'Siempre es bueno tener una estimación del tiempo para el proyecto, si es posible.', time: 'Hace 30 min'} ]},
    { title: 'Se busca programador front-end para proyecto personal', author: 'Javier D.', time: 'Hace 5 días', replies: 3, content: 'Estoy desarrollando una aplicación y necesito un programador que me ayude con la parte visual. Contacto por interno.', comments: [ {author: 'Pedro A.', text: 'Hola, me interesa tu proyecto. Te envié un mensaje directo.', time: 'Hace 1 día'}, {author: 'Martín T.', text: 'También estoy disponible, tengo experiencia con React y Next.js.', time: 'Hace 1 día'}, {author: 'Carlos V.', text: 'Manda más info, yo podría ser de ayuda.', time: 'Hace 2 días'} ]},
    { title: 'Herramientas de marketing digital para freelancers', author: 'Ana G.', time: 'Hace 2 semanas', replies: 9, content: 'Quiero empezar a promocionar mis servicios de freelancer, ¿qué herramientas recomiendan para gestionar redes sociales o email marketing?', comments: [ {author: 'Sofía R.', text: 'Para email marketing, Mailchimp es muy intuitivo y fácil de usar.', time: 'Hace 1 semana'}, {author: 'Juan G.', text: 'Yo uso Buffer para programar publicaciones en redes sociales.', time: 'Hace 1 semana'}, {author: 'Laura P.', text: 'Canva es esencial para crear contenido visual rápido y profesional.', time: 'Hace 1 semana'}, {author: 'Carlos V.', text: 'Te recomiendo HootSuite para la gestión de varias cuentas a la vez.', time: 'Hace 1 semana'}, {author: 'Ana P.', text: 'HubSpot tiene herramientas gratuitas de CRM y marketing que son geniales.', time: 'Hace 1 semana'}, {author: 'Pedro A.', text: 'Pardot es genial para la automatización, pero es más avanzado y de pago.', time: 'Hace 1 semana'}, {author: 'Martín T.', text: 'Lo más importante es la estrategia, la herramienta es solo un medio.', time: 'Hace 1 semana'}, {author: 'Laura D.', text: 'Trello o Asana también sirven para organizar tu calendario de contenido.', time: 'Hace 2 semanas'}, {author: 'Daniela G.', text: 'Si buscas algo simple y gratis, Later es bueno para Instagram.', time: 'Hace 2 semanas'} ]},
    { title: 'Cómo lidiar con clientes difíciles', author: 'Roberto C.', time: 'Hace 1 mes', replies: 6, content: 'He tenido un par de experiencias malas con clientes que cambian de opinión constantemente. ¿Algún consejo para gestionar estas situaciones de manera profesional?', comments: [ {author: 'Juan G.', text: 'Establecer un contrato claro desde el principio es fundamental.', time: 'Hace 2 semanas'}, {author: 'Sofía R.', text: 'Hay que definir el número de revisiones en el contrato, así evitas cambios infinitos.', time: 'Hace 2 semanas'}, {author: 'Carlos V.', text: 'La comunicación constante es clave. Un reporte semanal ayuda a que el cliente sepa en qué vas.', time: 'Hace 3 semanas'}, {author: 'Ana P.', text: 'A veces, lo mejor es ser firme y decir "eso no estaba en el acuerdo".', time: 'Hace 3 semanas'}, {author: 'Pedro A.', text: 'Documenta todo. Cada cambio o solicitud debe quedar por escrito.', time: 'Hace 4 semanas'}, {author: 'Martín T.', text: 'Define los hitos del proyecto y cobra por cada uno que se cumpla.', time: 'Hace 4 semanas'} ]},
    { title: 'Recomendaciones de portafolio para fotógrafos', author: 'Fernanda L.', time: 'Hace 1 mes', replies: 8, content: 'Estoy creando mi portafolio digital, ¿qué plataformas me recomiendan para mostrar mi trabajo? Busco algo profesional y fácil de usar.', comments: [ {author: 'Juan G.', text: 'Behance es muy popular y la comunidad es activa.', time: 'Hace 1 mes'}, {author: 'Sofía R.', text: 'Squarespace es ideal para portafolios, muy limpio y profesional.', time: 'Hace 1 mes'}, {author: 'Carlos V.', text: 'Flickr aún tiene una comunidad grande de fotógrafos.', time: 'Hace 1 mes'}, {author: 'Ana P.', text: 'Adobe Portfolio viene incluido con la suscripción a Creative Cloud.', time: 'Hace 1 mes'}, {author: 'Pedro A.', text: 'SmugMug es más enfocado en la venta de fotos, pero su portafolio es muy bueno.', time: 'Hace 1 mes'}, {author: 'Martín T.', text: 'Un sitio web propio con WordPress y un tema de portafolio es la mejor opción a largo plazo.', time: 'Hace 1 mes'}, {author: 'Laura D.', text: '500px es una plataforma para fotógrafos serios y la calidad es alta.', time: 'Hace 1 mes'}, {author: 'Daniela G.', text: 'Pinterest es excelente para generar tráfico a tu sitio web.', time: 'Hace 1 mes'} ]},
    { title: '¿Es mejor trabajar con un solo cliente grande o varios pequeños?', author: 'Pedro A.', time: 'Hace 2 meses', replies: 4, content: 'Me surgió la oportunidad de un contrato a largo plazo, pero me da miedo depender de un solo cliente. ¿Qué opinan?', comments: [ {author: 'Juan G.', text: 'Un solo cliente grande te da estabilidad, pero es riesgoso.', time: 'Hace 2 meses'}, {author: 'Sofía R.', text: 'Varios clientes pequeños te dan más libertad y menos dependencia.', time: 'Hace 2 meses'}, {author: 'Carlos V.', text: 'Lo ideal es tener una mezcla de ambos, si es posible.', time: 'Hace 2 meses'}, {author: 'Ana P.', text: 'Depende de tus objetivos. Un cliente grande puede ser un trampolín para tu carrera.', time: 'Hace 2 meses'} ]},
    { title: 'Consejos para programadores que quieren empezar como freelance', author: 'Mariana Z.', time: 'Hace 2 meses', replies: 2, content: 'Soy programadora con 3 años de experiencia en una empresa, pero quiero dar el salto al mundo freelance. ¿Qué es lo primero que debo saber?', comments: [ {author: 'Juan G.', text: 'Ten un portafolio sólido y define tus precios antes de empezar.', time: 'Hace 2 meses'}, {author: 'Sofía R.', text: 'Networking es clave. Conoce a otros freelancers y clientes potenciales.', time: 'Hace 2 meses'} ]},
    { title: 'Recursos para aprender sobre SEO', author: 'Diego M.', time: 'Hace 3 meses', replies: 7, content: 'Quiero añadir servicios de SEO a mi oferta, pero necesito aprender más. ¿Qué cursos o recursos recomiendan?', comments: generateRandomComments(7)},
    { title: 'Opiniones sobre plataformas de freelancers', author: 'Camila J.', time: 'Hace 3 meses', replies: 5, content: 'He visto varias plataformas como Upwork, Fiverr, y otras. ¿Cuál ha sido su experiencia? ¿Alguna es mejor para un principiante?', comments: generateRandomComments(5)},
    { title: 'Cómo crear un buen contrato de servicios', author: 'Ignacio S.', time: 'Hace 4 meses', replies: 8, content: 'Siempre me han dado contratos los clientes, pero quiero crear mi propia plantilla. ¿Qué puntos clave debo incluir para proteger mi trabajo?', comments: generateRandomComments(8)},
    { title: 'Mejores nichos para diseñadores gráficos en 2024', author: 'Valentina O.', time: 'Hace 4 meses', replies: 6, content: 'El diseño gráfico es un mercado saturado. ¿Han notado algún nicho que tenga alta demanda actualmente?', comments: generateRandomComments(6)},
    { title: 'Ideas de proyectos para practicar React', author: 'Luis B.', time: 'Hace 5 meses', replies: 9, content: 'Ya terminé un par de tutoriales de React y ahora quiero construir algo por mi cuenta. ¿Qué tipo de proyectos me recomiendan?', comments: generateRandomComments(9)},
    { title: 'Diferencias entre diseñador UX y UI', author: 'Elena F.', time: 'Hace 5 meses', replies: 7, content: 'Siempre me confunden los términos, ¿podrían explicarme de forma sencilla las responsabilidades de cada uno?', comments: generateRandomComments(7)},
    { title: 'Herramientas de gestión de proyectos para equipos pequeños', author: 'Gabriela K.', time: 'Hace 6 meses', replies: 5, content: 'Somos un equipo de 3 freelancers y queremos organizarnos mejor. ¿Qué herramientas usan para asignar tareas y comunicarnos?', comments: generateRandomComments(5)},
    { title: 'Consejos para negociar tarifas', author: 'Javier P.', time: 'Hace 6 meses', replies: 6, content: 'Me cuesta mucho decir mi precio y siempre termino cobrando menos de lo que debería. ¿Cómo puedo ser más firme en las negociaciones?', comments: generateRandomComments(6)},
    { title: 'Cómo escribir una propuesta de proyecto efectiva', author: 'Andrea L.', time: 'Hace 7 meses', replies: 8, content: 'He notado que mis propuestas no siempre son aceptadas. ¿Hay alguna estructura o tip que pueda mejorar mis propuestas?', comments: generateRandomComments(8)},
    { title: 'Mejores prácticas para el código en JavaScript', author: 'Tomás R.', time: 'Hace 7 meses', replies: 5, content: 'Quiero mejorar la calidad de mi código. ¿Alguna recomendación sobre linters, formateadores o patrones de diseño que deba seguir?', comments: generateRandomComments(5)},
    { title: 'Errores comunes al empezar como freelance', author: 'Isabel V.', time: 'Hace 8 meses', replies: 7, content: 'Estoy a punto de empezar mi camino. ¿Qué errores debería evitar para no fracasar en el intento?', comments: generateRandomComments(7)},
    { title: 'Cómo crear una marca personal sólida', author: 'Martín A.', time: 'Hace 8 meses', replies: 9, content: 'Sé que la marca personal es importante, pero no sé por dónde empezar. ¿Qué pasos recomiendan para construir una buena reputación?', comments: generateRandomComments(9)},
    { title: 'La importancia de los tests unitarios en el desarrollo web', author: 'Pablo S.', time: 'Hace 9 meses', replies: 6, content: 'Soy un poco nuevo en esto de los tests y no sé si son tan importantes. ¿Podrían convencerme de por qué debería usarlos?', comments: generateRandomComments(6)},
    { title: 'Cómo facturar de forma profesional', author: 'Florencia B.', time: 'Hace 9 meses', replies: 8, content: 'Estoy cobrando mis servicios, pero me gustaría saber si hay algún sistema o software que me recomienden para gestionar mis facturas de manera más ordenada.', comments: generateRandomComments(8)},
    { title: 'Estrategias para encontrar clientes en redes sociales', author: 'Lucas C.', time: 'Hace 10 meses', replies: 5, content: 'Quiero usar mi Instagram y LinkedIn para conseguir clientes, pero no sé qué tipo de contenido publicar. ¿Alguna idea?', comments: generateRandomComments(5)},
    { title: 'Diferencias entre Python y JavaScript', author: 'Diego M.', time: 'Hace 10 meses', replies: 7, content: 'Soy programador de Python y estoy pensando en aprender JavaScript. ¿Qué tan diferentes son y qué curva de aprendizaje tiene?', comments: generateRandomComments(7)},
    { title: 'La importancia de la comunicación en proyectos a distancia', author: 'Matias S.', time: 'Hace 1 año', replies: 9, content: 'He notado que la mala comunicación es la causa de la mayoría de los problemas en proyectos remotos. ¿Cómo podemos mejorar?', comments: generateRandomComments(9)},
    { title: 'Cómo gestionar el estrés del trabajo freelance', author: 'Carla C.', time: 'Hace 1 año', replies: 5, content: 'Me siento abrumada por la incertidumbre y el horario. ¿Algún consejo para gestionar el estrés y el burnout?', comments: generateRandomComments(5)},
    { title: 'Plataformas de gestión de proyectos', author: 'Jorge L.', time: 'Hace 1 año', replies: 6, content: 'Estoy buscando una plataforma para gestionar mis proyectos y clientes. ¿Cuáles me recomiendan?', comments: generateRandomComments(6)},
    { title: 'Recursos para aprender SQL', author: 'Sofia B.', time: 'Hace 1 año', replies: 8, content: 'Necesito aprender SQL para un proyecto. ¿Algún curso o tutorial que me recomienden?', comments: generateRandomComments(8)},
    { title: 'Mejores prácticas para la seguridad web', author: 'Andrés P.', time: 'Hace 1 año', replies: 7, content: 'Como desarrollador, me preocupa la seguridad. ¿Qué prácticas recomiendan para proteger las aplicaciones web?', comments: generateRandomComments(7)},
    { title: 'Ideas de contenido para un blog de freelancer', author: 'Laura C.', time: 'Hace 1 año', replies: 5, content: 'Quiero empezar un blog para atraer clientes. ¿Qué temas les parecen interesantes?', comments: generateRandomComments(5)},
    { title: 'Cómo crear un buen portafolio de redacción', author: 'Maria P.', time: 'Hace 1 año', replies: 9, content: 'Soy escritora freelance y necesito un portafolio. ¿Algún consejo para hacerlo destacar?', comments: generateRandomComments(9)},
    { title: 'Cómo hacer networking en línea', author: 'Esteban F.', time: 'Hace 1 año', replies: 6, content: 'Me cuesta mucho conectar con otros profesionales. ¿Qué estrategias de networking en línea funcionan?', comments: generateRandomComments(6)},
    { title: 'La importancia de la especialización', author: 'Romina D.', time: 'Hace 1 año', replies: 7, content: 'Soy una freelancer generalista, pero he oído que especializarse es mejor. ¿Qué opinan?', comments: generateRandomComments(7)},
    { title: 'Cómo usar LinkedIn para encontrar clientes', author: 'Diego L.', time: 'Hace 1 año', replies: 8, content: 'Quiero empezar a usar LinkedIn para conseguir clientes, ¿algún consejo?', comments: generateRandomComments(8)},
    { title: 'Cómo gestionar las finanzas como freelance', author: 'Paula G.', time: 'Hace 1 año', replies: 5, content: 'Llevo un par de meses como freelance y me cuesta mucho organizar mis finanzas. ¿Qué herramientas o consejos me dan?', comments: generateRandomComments(5)},
    { title: 'Cómo manejar la retroalimentación negativa', author: 'Ramiro N.', time: 'Hace 1 año', replies: 9, content: 'Un cliente me dio una crítica muy dura. ¿Cómo se gestionan estas situaciones sin tomárselo personal?', comments: generateRandomComments(9)},
    { title: 'Consejos para diseñadores gráficos que quieren especializarse en packaging', author: 'Ana C.', time: 'Hace 1 año', replies: 6, content: 'Me interesa el diseño de packaging, pero no sé por dónde empezar. ¿Qué herramientas o cursos recomiendan?', comments: generateRandomComments(6)},
    { title: 'Cómo crear un buen currículum vitae para el sector tech', author: 'Javier G.', time: 'Hace 1 año', replies: 7, content: 'Estoy actualizando mi CV, ¿qué información debo destacar para conseguir un puesto en el sector tech?', comments: generateRandomComments(7)},
    { title: 'La importancia del branding personal en la industria creativa', author: 'Daniela R.', time: 'Hace 1 año', replies: 5, content: 'Soy fotógrafa y me gustaría saber por qué es tan importante el branding personal en mi campo.', comments: generateRandomComments(5)},
    { title: 'Cómo hacer un buen pitch de ventas', author: 'Fernando M.', time: 'Hace 1 año', replies: 8, content: 'Necesito mejorar mis habilidades de ventas. ¿Algún consejo para crear un pitch efectivo?', comments: generateRandomComments(8)},
    { title: 'Diferencias entre desarrollo web front-end y back-end', author: 'Lucía P.', time: 'Hace 1 año', replies: 9, content: 'Soy nueva en el desarrollo web y me gustaría entender las diferencias entre front-end y back-end.', comments: generateRandomComments(9)},
    { title: 'Herramientas de automatización para freelancers', author: 'Alejandro C.', time: 'Hace 1 año', replies: 6, content: 'Quiero automatizar tareas repetitivas. ¿Qué herramientas me recomiendan?', comments: generateRandomComments(6)},
    { title: 'Cómo encontrar clientes de forma pasiva', author: 'Florencia D.', time: 'Hace 1 año', replies: 7, content: 'Estoy cansada de buscar clientes activamente. ¿Alguna estrategia para que los clientes me encuentren a mí?', comments: generateRandomComments(7)},
    { title: 'Cómo crear una cartera de servicios atractiva', author: 'Gabriela S.', time: 'Hace 1 año', replies: 5, content: 'Quiero ofrecer un paquete de servicios. ¿Qué debo tener en cuenta para que sea atractivo para los clientes?', comments: generateRandomComments(5)},
    { title: 'Consejos para trabajar desde casa', author: 'Sofía L.', time: 'Hace 1 año', replies: 8, content: 'Soy nueva en el teletrabajo y me cuesta ser productiva. ¿Algún consejo para mantener el enfoque?', comments: generateRandomComments(8)},
    { title: 'Cómo lidiar con la soledad del freelance', author: 'Martín V.', time: 'Hace 1 año', replies: 9, content: 'Me siento un poco solo trabajando desde casa. ¿Alguna forma de conectar con otros freelancers?', comments: generateRandomComments(9)},
    { title: 'Cómo proteger mi propiedad intelectual', author: 'Valeria P.', time: 'Hace 1 año', replies: 6, content: 'Como diseñadora, me preocupa que roben mis diseños. ¿Cómo puedo proteger mi propiedad intelectual?', comments: generateRandomComments(6)},
    { title: 'Mejores nichos para redactores freelance', author: 'Andrés Z.', time: 'Hace 1 año', replies: 7, content: 'Soy redactor y me gustaría especializarme. ¿Qué nichos están en alta demanda?', comments: generateRandomComments(7)},
    { title: 'Cómo optimizar un perfil de LinkedIn', author: 'Carla R.', time: 'Hace 1 año', replies: 5, content: 'Quiero usar mi perfil de LinkedIn para atraer más clientes. ¿Algún consejo para optimizarlo?', comments: generateRandomComments(5)},
    { title: 'Cómo gestionar el tiempo de forma efectiva', author: 'Ignacio G.', time: 'Hace 1 año', replies: 8, content: 'Siempre siento que el día no me alcanza. ¿Alguna técnica para gestionar mejor mi tiempo?', comments: generateRandomComments(8)},
];